# Site
repository: Jeongseokjin/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 정석진
title: 백엔드 개발자
email: sj_jeong384@naver.com
website: https://github.com/Jeongseokjin

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: Jeongseokjin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: 블로그
    icon: fas fa-blog
    url: https://1223tjrwls.tistory.com/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/jeongseokjin.jpg
about_content: | # this will include new lines to allow paragraphs
  백엔드 개발을 좋아하며, 문제 해결자(problem solver)로 성장하고자 합니다.<br>
              개발을 문제 해결을 위한 도구로 보고, 단순히 효율화나 자동화에 그치지 않고 더 넓은 범위의 문제를 해결하는 데 초점을 맞춥니다.<br>
              이를 통해 조직의 시간과 비용을 절감하고, 업무를 자동화하며, 근본적인 비효율을 해소하여 조직의 성공에 기여하고자 합니다.

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Java, Spring Boot, Spring Data JPA, Spring Cloud Stream
          - Kafka, Event Sourcing
          - Hibernate, Flyway
          - JUnit5, Mockito, Testcontainers
      
      - layout: left
        title: Cloud & DevOps
        description: | # this will include new lines to allow paragraphs
          - AWS (EC2, ELB, Route 53, S3, RDS, CloudWatch)
          - GitHub Actions, CodePipeline
          - Docker, Kubernetes
          - Prometheus, Grafana
      
      - layout: left
        title: Database
        description: | # this will include new lines to allow paragraphs
          - MySQL, JPQL, QueryDSL, Flyway
      
      - layout: left
        title: Frontend
        description: | # this will include new lines to allow paragraphs
          - React.js, Next.js, Three.js
          - HTML, CSS3, JavaScript (ES6)
      
      - layout: left
        title: Tools & Collaboration
        description: | # this will include new lines to allow paragraphs
          - IntelliJ, VS Code
          - Git, GitHub
          - Jira, Slack

  - title: Projects & Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IT MOO U
        sub_title: 백엔드 개발자 | 물류 최적화 개발자
        caption: 2024.03 - 현재
        # GitHub 링크가 HTML에서 제거되었으므로 여기서도 제거합니다
        technologies: Java, Spring Boot, Kafka, Spring Cloud Stream, MongoDB, Docker, Kubernetes, AWS 기술 스택 활용
        description: | # this will include new lines to allow paragraphs
          - 팔레트 물류 최적화를 위한 MVP를 설계 및 개발하며 초기 서비스 검증 주도
          - Kafka 기반 이벤트 드리븐 아키텍쳐(EDA)를 설계해 시스템 간 비동기 통신 최적화
          - ECS 기반 배포 파이프라인을 구축해 운영비용 15% 절감 및 배포 안정성 확보
          - AI 기술을 전략적으로 활용하여 기획부터 배포까지의 프로세스를 효율화함으로써, 초기 제품 검증 단계를 대폭 가속화
          - 물류 시스템의 확장성을 고려한 클라우드 네이티브 아키텍처 설계
      
      - layout: left
        title: WOORI ZIP
        caption: 2024.10.21 - 2024.12.06
        link: https://github.com/woorifisa-projects-3rd/woori-zip-BE/tree/main
        link_text: Woori Zip Git Hub
        technologies: React, Next.js, Spring Boot, JPA, MariaDB, AWS(EC2, S3, RDS, Route 53, CodeDeploy), Prometheus, Kakao Maps API 기술 스택 활용
        description: | # this will include new lines to allow paragraphs
          - Spring Boot와 ML 모델을 활용한 금융 데이터 기반 맞춤형 부동산 추천 시스템 설계 및 구현
          - OAuth 2.0과 JWT를 활용한 우리은행 계정 연동 및 권한별 인증 시스템 구축
          - AOP 기반 로깅 시스템을 주도적으로 개선하여 MDC와 ELK 스택으로 API 요청/응답 추적 및 실시간 모니터링 체계 확립
          - AWS(EC2, RDS, S3) 기반 클라우드 인프라를 설계하고 CI/CD 파이프라인 구축으로 배포 자동화
          - 사용자 주택 조건 및 금융 정보에 따른 최적 대출 상품 매칭 알고리즘 개발
      
      - layout: left
        title: (주)대원프리시전
        sub_title: 설비OP 자동차 ESS 설비 기술 주임
        caption: 2020.10 ~ 2024.04 (3년 6개월)
        description: | # this will include new lines to allow paragraphs
          - **비용 최적화 및 불량률 감소**
            - 배터리 사업의 경쟁력을 위해 비용 절감을 최우선 목표로 설정하고, 불량률 감소에 주력
            - SCADA 시스템을 도입해 설비 데이터를 실시간으로 수집 및 시각화하며, 장력 불규칙성이 주요 원인임을 규명
          - **설비 개선 및 자동화 도입**
            - 설계팀과 협업하여 전극 장력 조절 롤러 시스템을 개발하고, 센서 데이터를 PLC 시스템과 연동해 장력을 자동으로 조절할 수 있는 시스템 설계
            - 작업자가 설비 상태를 직관적으로 확인할 수 있도록 HMI 인터페이스를 도입하고, 장력이 임계값을 초과하면 자동으로 설비를 정지하는 기능 구현
          - **효율적인 협업과 소통**
            - 설계팀과 현장팀 간의 상이한 주장을 데이터로 검증하여 명확한 해결책을 도출
            - 상대방의 전문성을 존중하며, 데이터를 기반으로 공감대를 형성하는 소통 방식을 통해 팀 내 갈등을 완화
      
      - layout: left
        title: (주)이한산업
        sub_title: 설비OP 설비 개발 사원
        caption: 2020.03 ~ 2020.09 (7개월)
        description: | # this will include new lines to allow paragraphs
          - **유압 프레스 설비 프로젝트 참여**
            - 친환경 소재 압축을 위한 유압 프레스 설비의 개발과 안정화 작업을 팀과 함께 수행
            - 설비 안전성을 강화하기 위해 안전 센서 및 비상 정지 장치의 도입 및 개선 논의에 적극 참여
          - **팀 간 협업 및 문제 해결**
            - 설계팀, 생산팀과 긴밀히 협력하여 설비 운영 중 발생 가능한 위험 요소를 파악하고 개선 방안 마련

  - title: Article # Title for the section (HTML에서는 "Article"로 변경됨)
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 기술 서적 리뷰 참여
        description: | # this will include new lines to allow paragraphs
          - **&lt;코딩 자율학습 자바 입문&gt; 베타 학습단**
            - [코딩 자율학습 자바 입문 리뷰.pdf](https://www.notion.so/11f81bfd238b804fb737cccd27bebf52?pvs=4#1c181bfd238b80b1a9abfb792d61d9c8)
            - [학습단 참여 확인서_정석진.pdf](https://rune-lan-2a9.notion.site/1b981bfd238b8054973de480f30a200e?pvs=4)
          - **[길벗] &lt;아는 만큼 보이는 IT 지식&gt; 베타 리뷰**
            - [베타 리더 리뷰](https://www.notion.so/11f81bfd238b804fb737cccd27bebf52?pvs=4#1c181bfd238b80c99e87e89b4c80dea4)
      
      - layout: left
        title: 개인 블로그 활동
        link: https://1223tjrwls.tistory.com/
        link_text: Blog
        description: | # this will include new lines to allow paragraphs
          - 이슈 해결 사례 및 기술 노하우 공유
          - 물류 최적화 및 이벤트 드리븐 아키텍처 관련 기술 분석

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 우리 FISA 3기
        caption: 2024.07 - 2024.12
        description: | # this will include new lines to allow paragraphs
          - AWS 기반 클라우드 서비스 개발, 서버 배포 및 관리 교육
          - Java와 Spring Boot로 RESTful API 설계 및 구현 학습
          - MySQL, JPA로 데이터베이스 연동 및 쿼리 작성 (JPQL, QueryDSL) 실습
          - Flyway로 데이터베이스 스키마 버전 관리 및 자동 마이그레이션 학습
          - WOORI ZIP 프로젝트 진행 (2024.10.21 - 2024.12.06), 풀스택 및 DevOps 기술 학습
      
      - layout: left
        title: 청주대학교
        caption: 2015.03 - 2021.02
        description: | # this will include new lines to allow paragraphs
          - 전공: 컴퓨터정보공학과
          - 학생회장 활동으로 리더십, 협동심, 문제해결능력 강화

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag