# Site
repository: Jeongseokjin/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 정석진
title: 백엔드 서버 엔지니어 | AI 기반 물류 최적화 개발자
email: sj_jeong384@naver.com
website: https://github.com/Jeongseokjin

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: Jeongseokjin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: 블로그
    icon: fas fa-blog
    url: https://1223tjrwls.tistory.com/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/jeongseokjin.jpg
about_content: | # this will include new lines to allow paragraphs
Java/Spring 백엔드 개발자로서 "가성비 좋은 개발"을 추구합니다. AI 물류 최적화 솔루션 Allogic에서 물류 효율화에 집중하고 있습니다.

임베디드 설비 분야 경험을 통해 다양한 이해관계자와 소통하며 데이터 기반 문제 해결 역량을 키웠습니다. 설계팀과 현장팀의 갈등을 데이터로 해결했던 경험은 개발자와 사용자 간 요구사항 격차를 메우는 자산이 되었습니다.

코드 결벽증을 바탕으로 깔끔한 코드를 지향하며, 사용자 경험을 이해하는 개발자가 되기 위해 TDD와 애자일 방식을 선호합니다. 개발 지식과 경험을 블로그에 기록하며 지속적인 성장을 추구합니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IT MOO U
        # link: https://mooexample.com/
        # link_text: Company Website
        sub_title: 백엔드 개발자 | AI 기반 물류 최적화 개발자
        caption: 2024.03 - 현재
        quote: >
          Allogic - AI 기반 물류 최적화 솔루션 개발(스타트업)
        description: | # this will include new lines to allow paragraphs
          - 작은 스타트업 환경에서 기획부터 개발, 배포까지 풀스택으로 참여한 경험
          - 주로 Kafka를 활용한 이벤트 드리븐 아키텍처(EDA) 패러다임 설계에 집중
          - 로그 수집 시스템 아키텍처 설계 및 초기 개발 작업 진행 중
          - 물류 최적화를 위한 데이터 처리 및 분석 파이프라인 구조 기획
          - 마이크로서비스 간 비동기 통신을 위한 이벤트 기반 시스템 아키텍처 설계
          - 물류 관련 AI 알고리즘 개발을 위한 데이터 파이프라인 구성 참여
      
      - layout: left
        title: (주)대원프리시전
        # link: https://daeown.com/
        # link_text: Company Website
        sub_title: 설비OP 자동차 ESS 설비 기술 주임
        caption: 2020.10 ~ 2024.04 (44개월)
        quote: >
          설비 엔지니어로서 테스트 위주의 설비 개발 및 문제 해결
        description: | # this will include new lines to allow paragraphs
          - **비용 최적화 및 불량률 감소**
            - 배터리 사업의 경쟁력을 위해 비용 절감을 최우선 목표로 설정하고, 불량률 감소에 주력
            - SCADA 시스템을 도입해 설비 데이터를 실시간으로 수집 및 시각화하며, 장력 불규칙성이 주요 원인임을 규명
          - **설비 개선 및 자동화 도입**
            - 설계팀과 협업하여 전극 장력 조절 롤러 시스템을 개발하고, 센서 데이터를 PLC 시스템과 연동해 장력을 자동으로 조절할 수 있는 시스템 설계
            - 작업자가 설비 상태를 직관적으로 확인할 수 있도록 HMI 인터페이스를 도입하고, 장력이 임계값을 초과하면 자동으로 설비를 정지하는 기능 구현
          - **효율적인 협업과 소통**
            - 설계팀과 현장팀 간의 상이한 주장을 데이터로 검증하여 명확한 해결책을 도출
            - 상대방의 전문성을 존중하며, 데이터를 기반으로 공감대를 형성하는 소통 방식을 통해 팀 내 갈등을 완화
      
      - layout: left
        title: (주)이한산업
        # link: https://leehan.com/
        # link_text: Company Website
        sub_title: 설비OP 설비 개발 사원
        caption: 2020.03 ~ 2020.09 (7개월)
        quote: >
          유압 프레스 설비의 안전성 확보와 효율성 향상
        description: | # this will include new lines to allow paragraphs
          - **유압 프레스 설비 프로젝트 참여**
            - 친환경 소재 압축을 위한 유압 프레스 설비의 개발과 안정화 작업을 팀과 함께 수행
            - 설비 안전성을 강화하기 위해 안전 센서 및 비상 정지 장치의 도입 및 개선 논의에 적극 참여
          - **팀 간 협업 및 문제 해결**
            - 설계팀, 생산팀과 긴밀히 협력하여 설비 운영 중 발생 가능한 위험 요소를 파악하고 개선 방안 마련
            - 설비의 효율성과 안전성을 유지하며 작업 환경을 최적화하기 위한 아이디어를 팀 내 공유하고 논의
          - **설비 안정성 및 테스트 지원**
            - 설비 프로토타입 테스트 과정에 참여해 데이터를 기반으로 설비 성능 및 안전 요소를 평가
            - 안전과 생산성을 모두 고려한 개선 방향을 제안하고 설비 개발 과정에 반영

  - title: 핵심 역량
    layout: list
    content:
      - layout: left
        title: 이벤트 기반 아키텍처(EDA) 설계
        description: | # this will include new lines to allow paragraphs
          - 스타트업 환경에서 Kafka를 활용한 이벤트 기반 아키텍처 설계 및 구현
          - 물류 시스템의 확장성과 유연성을 고려한 이벤트 드리븐 모델 설계
          - 로그 수집 및 분석을 위한 비동기 통신 구조 기획
          - 마이크로서비스 아키텍처에서 데이터 일관성 확보를 위한 이벤트 소싱 패턴 적용
      
      - layout: left
        title: 시스템 개발 및 유지보수
        description: | # this will include new lines to allow paragraphs
          - **IT MOO U**
            - Kafka를 활용한 이벤트 드리븐 아키텍처(EDA) 패러다임 설계 및 개발
            - 물류 최적화를 위한 데이터 처리 및 분석 파이프라인 구축
            - 로그 수집 시스템 아키텍처 설계 및 초기 개발 주도
          - **(주)대원프리시전**
            - SCADA 시스템을 도입해 설비 데이터 실시간 수집 및 시각화 구현
            - 센서 데이터를 PLC 시스템과 연동한 자동 조절 시스템 설계 참여
            - HMI 인터페이스 도입 및 임계값 기반 자동 정지 기능 구현
          - **(주)이한산업**
            - 유압 프레스 설비 안전성 강화를 위한 안전 센서 및 비상 정지 장치 개선
            - 설비 프로토타입 테스트 과정 참여 및 데이터 기반 성능 평가
      
      - layout: left
        title: 클라우드 및 DevOps
        description: | # this will include new lines to allow paragraphs
          - AWS Cloud 환경에서 서비스 아키텍처 설계 및 구현
          - Docker 및 Kubernetes를 활용한 컨테이너 기반 배포 환경 구성
          - CI/CD 파이프라인 구축으로 배포 프로세스 자동화
          - Prometheus, Grafana를 활용한 모니터링 시스템 구축
      
      - layout: left
        title: 협업 및 의사소통
        description: | # this will include new lines to allow paragraphs
          - 다양한 이해관계자(설계팀, 현장팀, 생산팀) 간 효과적인 커뮤니케이션 주도
          - 설계팀과 현장팀 간 상이한 주장을 데이터로 검증하여 명확한 해결책 도출
          - 팀 내 갈등 최소화를 위한 데이터 기반 의사결정 프로세스 적용
          - 사용자 중심 설계 및 애자일 방식의 개발 경험
      
      - layout: left
        title: 기술 서적 리뷰 참여
        description: | # this will include new lines to allow paragraphs
          - <코딩 자율학습 자바 입문> 베타 학습단
            - [학습단 참여 확인서_정석진.pdf](https://rune-lan-2a9.notion.site/1b981bfd238b8054973de480f30a200e?pvs=4)
          - [길벗] <아는 만큼 보이는 IT 지식> 베타 리뷰
            - IT 분야 기초 지식 및 최신 기술 트렌드에 대한 전문적 리뷰 제공
            - 개발자 관점에서의 피드백 및 내용 개선 제안
      
      - layout: left
        title: 개인 블로그 활동
        description: | # this will include new lines to allow paragraphs
          - 개발 과정에서 습득한 지식과 경험을 [블로그](https://1223tjrwls.tistory.com/)에 꾸준히 기록
          - 이슈 해결 사례 및 기술 노하우 공유
          - 물류 최적화 및 이벤트 드리븐 아키텍처 관련 기술 분석

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        quote: >
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - Languages: Java
          - Frameworks: Spring Boot, Spring Data JPA, Spring Cloud Stream, Spring Kafka, QueryDSL
          - Event-Driven: Kafka, Kafka Streams, Event Sourcing
          - Tools & Libraries: Hibernate, Flyway, Swagger, Postman, REST Assured, Cypress, AOP, MDC
          - Testing: JUnit5, Mockito, Testcontainers
      
      - layout: left
        title: Database
        quote: >
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - MySQL
          - 연동 및 쿼리 최적화: JPQL, QueryDSL
          - 스키마 관리: Flyway
      
      - layout: left
        title: Cloud & DevOps
        quote: >
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - AWS: EC2, Elastic Load Balancer (ELB), Route 53, S3
          - CI/CD: GitHub Actions, CodePipeline
          - Monitoring: Prometheus, Grafana
          - Message Broker: Apache Kafka, Kafka Streams
          - Containerization: Docker, Kubernetes
      
      - layout: left
        title: Frontend
        quote: >
          현재 업무에 사용중 혹은 사용했던 기술들입니다.
        description: | # this will include new lines to allow paragraphs
          - React.js
          - Next.js
          - Three.js

  - title: Project # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Allogic - 물류 이벤트 플랫폼
        link: https://github.com/Jeongseokjin/allogic-platform
        caption: 2024.04 - 현재
        quote: >
          AI 기반 물류 최적화 솔루션
        description: | # this will include new lines to allow paragraphs
          - 스타트업 환경에서 이벤트 드리븐 아키텍처(EDA) 패러다임 설계 참여
          - Java, Spring Boot, Kafka, Spring Cloud Stream, MongoDB, Docker, Kubernetes, AWS
          - 물류 시스템의 확장성을 고려한 클라우드 네이티브 아키텍처 설계
          - Allogic 물류 이벤트 플랫폼 현재 private 진행 중 (링크 불가)
      
      - layout: left
        title: WOORI ZIP
        link: https://github.com/woorifisa-projects-3rd/woori-zip-BE
        caption: 2024.10.21 - 2024.12.06
        quote: >
          AWS 기반 부동산 정보 플랫폼
        description: | # this will include new lines to allow paragraphs
          - 부동산 정보 제공 및 맞춤형 대출 추천 서비스를 제공하는 종합 플랫폼
          - Java, Spring Boot, Spring Data JPA, MySQL, AWS(EC2, RDS, S3), CI/CD
          - 클라우드 인프라 설계 및 배포 전략 수립, 모니터링 시스템 구축
          - [WOORI ZIP 부동산 플랫폼 포트폴리오 설명](https://rune-lan-2a9.notion.site/WOORI-ZIP-1b981bfd238b808cab35d1312bc1c810?pvs=4)

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 우리 FISA 3기
        caption: 2024.07 - 2024.12
        description: | # this will include new lines to allow paragraphs
          - AWS 기반 클라우드 서비스 개발, 서버 배포 및 관리 교육
          - Java와 Spring Boot로 RESTful API 설계 및 구현 학습
          - MySQL, JPA로 데이터베이스 연동 및 쿼리 작성 (JPQL, QueryDSL) 실습
          - Flyway로 데이터베이스 스키마 버전 관리 및 자동 마이그레이션 학습
          - WOORI ZIP 프로젝트 진행 (2024.10.21 - 2024.12.06), 풀스택 및 DevOps 기술 학습
      
      - layout: left
        title: 청주대학교
        caption: 2015.03 - 2021.02
        description: | # this will include new lines to allow paragraphs
          - 전공: 컴퓨터정보공학과
          - 학생회장 활동으로 리더십, 협동심, 문제해결능력 강화
          - 학과 프로젝트 및 행사 기획으로 유대감 증진
          - Java, C, Python, Database 등 기초 개발 언어 교육 수료

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag